name: Compilar
on:
  push:
    branches:
      - "main"
      - "qa"
      - "dev"
jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      solution: Dal
      version: 1.0.${{ github.run_number }}
      versionSuffix: ${{ github.ref_name }}
      username: leandrobaena@gmail.com
      ConnectionStrings__implantdent: Data Source=localhost;Initial Catalog=implantdentTest;User ID=sa;Password=dbatools.I0;Persist Security Info=False;Pooling=False;Multiple Active Result Sets=False;Connect Timeout=60;Encrypt=True;Trust Server Certificate=True;Command Timeout=0
    steps:

    #- name: Setup Java 17
    #  uses: actions/setup-java@v3.13.0
    #  with:
    #    java-version: 17
    #    distribution: oracle
    
    - name: Instalar SQL Server
      uses: potatoqualitee/mssqlsuite@v1.7
      with:
        install: sqlengine

    - name: Descarga del código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Crear base de datos de prueba
      run: sqlcmd -S localhost -i Dal.Test/installDb.sql -U sa -P dbatools.I0

    - name: Inicializar base de datos de prueba
      run: sqlcmd -S localhost -i Dal.Test/installDb.sql -U sa -P dbatools.I0

    - name: Cache de paquetes SonarCloud
      uses: actions/cache@v3
      with:
        path: ~/sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache de scanner SonarCloud
      id: cache-sonar-scanner
      uses: actions/cache@v3
      with:
        path: ./.sonar/scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    
    - name: Instalar scanner SonarCloud
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      run: 'dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner'
      
    - name: Inicializar SonarQube
      run: ./.sonar/scanner/dotnet-sonarscanner begin /k:"Implantdent_dal" /o:"implantdent" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

    - name: Adicionar repositorio
      run: dotnet nuget add source --username ${{ env.username }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/implantdent/index.json"

    - name: Compilar la solución
      run: dotnet build ${{ env.solution }}.sln -c Debug

    - name: Ejecutar pruebas unitarias
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
    - name: Finalizar SonarQube
      run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Crear el paquete Nuget
      if: ${{ github.ref_name == 'dev' || github.ref_name == 'qa' }}
      run: dotnet pack -c Release -p:PackageVersion=${{ env.version }}-${{ env.versionSuffix }} ${{ env.solution }}.sln

    - name: Crear el paquete Nuget
      if: ${{ github.ref_name == 'main' }}
      run: dotnet pack -c Release -p:PackageVersion=${{ env.version }} ${{ env.solution }}.sln

    - name: Construir artefacto
      if: ${{ github.ref_name == 'dev' || github.ref_name == 'qa' }}
      run: dotnet nuget push ${{ env.solution }}/bin/Release/${{ env.solution }}.${{ env.version }}-${{ env.versionSuffix }}.nupkg  --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/implantdent/index.json"

    - name: Construir artefacto
      if: ${{ github.ref_name == 'main' }}
      run: dotnet nuget push ${{ env.solution }}/bin/Release/${{ env.solution }}.${{ env.version }}.nupkg  --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/implantdent/index.json"